/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdv.sisac;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static pdv.sisac.pdv.base;
import static pdv.sisac.pdv.caminho;
import static pdv.sisac.pdv.porta;
import static pdv.sisac.pdv.precoItem_labe;
import static pdv.sisac.pdv.produto_field;
import static pdv.sisac.pdv.senha;
import static pdv.sisac.pdv.usuario;

/**
 *
 * @author meirinaldo
 */
public class pesquisar_produto extends javax.swing.JFrame {

    int id;
    private JTable tabela;
    private DefaultTableModel modelo =new DefaultTableModel();
        NumberFormat formatoMoeda = NumberFormat.getCurrencyInstance();
   

    public pesquisar_produto(){
        initComponents();
        criar_jtable();
        jScrollPane2.setViewportView(tabela);
        cod_label.requestFocus();
        cod_label.selectAll();
        
    }
    
    private void criar_jtable(){
        
        tabela = new JTable(modelo);
        modelo.addColumn("ID");
        modelo.addColumn("Produto");
        modelo.addColumn("Preço");
        modelo.addColumn("quantidade");
        
        tabela.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(120);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(50);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(20);
        
    }
    
    private void pesquisarIds(){
        String sql = "SELECT * FROM produtos WHERE id LIKE " + cod_label.getText().replace(" ", "");
         try{
                    Class.forName("com.mysql.jdbc.Driver");


                    try (Connection conexao = DriverManager.getConnection("jdbc:mysql://"+caminho+":"+porta+"/"+base, 
                                                                        usuario, senha); //Conecta-se ao banco de dados
                        Statement statement = conexao.createStatement()) {
                        
                        ResultSet resultSet = statement.executeQuery(sql);
                        
                     
                        while (resultSet.next()) {
                            id = resultSet.getInt("id");  
                            String produto = resultSet.getString("produto");  
                            Float preco_venda = resultSet.getFloat("preco_venda");  
                            int quantidade = resultSet.getInt("quatidade");  
                            
                      
                            modelo.addRow(new Object[] {id, produto,formatoMoeda.format(preco_venda),quantidade} );
                        }
                        
                          if (resultSet.first() == false){
                                  JOptionPane.showMessageDialog(this, "Produto não cadastrado!");
                             }
                        
                    }

                              }//fim do try     //fim do try     
                catch(ClassNotFoundException | SQLException e){     
                    System.err.println(e.getMessage());     
                }                
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cod_label = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pesquisar Produto");

        cod_label.setText("Insira ou passe seu código de barras!!!");
        cod_label.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cod_labelKeyPressed(evt);
            }
        });

        jScrollPane2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(cod_label, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cod_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cod_labelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cod_labelKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            pesquisarIds();        
            cod_label.selectAll();
            
            while (tabela.getModel().getRowCount() > 1)
                modelo.removeRow(0);
            
        }
        
    }//GEN-LAST:event_cod_labelKeyPressed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cod_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables


}
